"""Add external_id and additional fields to jobs table

Revision ID: c1b1cd50458b
Revises: cb0e0e7fd634
Create Date: 2025-08-04 15:29:31.623419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b1cd50458b'
down_revision: Union[str, Sequence[str], None] = 'cb0e0e7fd634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('source', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('company_logo_url', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('job_type', sa.Enum('FULL_TIME', 'PART_TIME', 'INTERNSHIP', 'CONTRACT', name='jobtypeenum'), nullable=True))

    op.execute("UPDATE jobs SET job_type = 'FULL_TIME' WHERE job_type IS NULL")

    op.alter_column('jobs', 'job_type', nullable=False)

    op.add_column('jobs', sa.Column('experience_level', sa.Enum('JUNIOR', 'MID', 'SENIOR', name='experiencelevel'), nullable=True))
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'job_type')
    op.drop_column('jobs', 'expires_at')
    op.drop_column('jobs', 'company_logo_url')
    op.drop_column('jobs', 'source')
    op.drop_column('jobs', 'external_id')
    # ### end Alembic commands ###
